In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
#from keras.layers import Dense, Activation, Flatten
from tensorflow.keras.layers import Dense, Activation, Flatten
import numpy as np

In [4]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
#define a document 
docs = ['Well done!','Good work','Great effort','nice work',
        'Excellent!','Weak','Poor effort!','not good','poor work',
        'Could have done better.']
#define a class label for doc 
labels = array([1,1,1,1,1,0,0,0,0,0])


In [7]:
#integer encode the document 
vocab_size = 50
encoded_doc = [one_hot(d,vocab_size) for d in docs]
print(encoded_doc)

[[19, 44], [48, 37], [13, 5], [46, 37], [48], [13], [19, 5], [41, 48], [19, 37], [14, 33, 44, 5]]


In [14]:
#pad document to max length of word 
max_length = 4
padded_doc = pad_sequences(encoded_doc,maxlen=max_length,padding='post')
print(padded_doc)

[[19 44  0  0]
 [48 37  0  0]
 [13  5  0  0]
 [46 37  0  0]
 [48  0  0  0]
 [13  0  0  0]
 [19  5  0  0]
 [41 48  0  0]
 [19 37  0  0]
 [14 33 44  5]]


In [28]:
#define the model
dim = 8
model =Sequential()
model.add(Embedding(vocab_size,8,input_length=max_length))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
#compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#summarize the model
print(model.summary())

#fit the model
model.fit(padded_doc,labels,epochs=50,verbose=0)

#evaluate the model
loss,accuracy = model.evaluate(padded_doc,labels,verbose=0)
print("Accuracy %f:"%(accuracy*100))
print("Loss ",loss)
          

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_11 (Embedding)     (None, 4, 8)              400       
_________________________________________________________________
flatten_7 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
Accuracy 60.000002:
Loss  0.6330486536026001
