In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
# Refernce Link ==> https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

<h1>One Hot Representation</h1>

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9445, 5954, 1510, 3224], [9445, 5954, 1510, 8519], [9445, 9704, 1510, 9646], [4073, 2450, 5768, 8592, 4852], [4073, 2450, 5768, 8592, 8773], [4193, 9445, 4639, 1510, 2680], [9989, 3392, 4709, 8592]]


<h1>Word Embedding Represntation
</h1>

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9445 5954 1510 3224]
 [   0    0    0    0 9445 5954 1510 8519]
 [   0    0    0    0 9445 9704 1510 9646]
 [   0    0    0 4073 2450 5768 8592 4852]
 [   0    0    0 4073 2450 5768 8592 8773]
 [   0    0    0 4193 9445 4639 1510 2680]
 [   0    0    0    0 9989 3392 4709 8592]]


In [ ]:
#Dimension vector size 
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[ 2.61882432e-02  4.07533981e-02  6.76042959e-03  4.93877865e-02
   -3.94345410e-02 -1.60716064e-02 -3.69771235e-02 -4.48753946e-02
   -1.59146562e-02 -1.35069713e-02]
  [ 2.61882432e-02  4.07533981e-02  6.76042959e-03  4.93877865e-02
   -3.94345410e-02 -1.60716064e-02 -3.69771235e-02 -4.48753946e-02
   -1.59146562e-02 -1.35069713e-02]
  [ 2.61882432e-02  4.07533981e-02  6.76042959e-03  4.93877865e-02
   -3.94345410e-02 -1.60716064e-02 -3.69771235e-02 -4.48753946e-02
   -1.59146562e-02 -1.35069713e-02]
  [ 2.61882432e-02  4.07533981e-02  6.76042959e-03  4.93877865e-02
   -3.94345410e-02 -1.60716064e-02 -3.69771235e-02 -4.48753946e-02
   -1.59146562e-02 -1.35069713e-02]
  [ 3.63668688e-02 -4.66466434e-02  2.94287540e-02 -3.85867357e-02
   -1.03674829e-04 -3.08752060e-05 -2.01164018e-02  3.55561860e-02
    4.75674607e-02 -3.79329436e-02]
  [ 2.64060497e-03 -3.26968320e-02  1.50458924e-02  3.50479521e-02
    1.43210180e-02 -2.58253459e-02 -7.88469240e-03  3.46909054e-02
   -6.75497204e-

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 9445, 5954, 1510, 3224])

In [17]:
print(model.predict(embedded_docs)[0])

[[ 2.6188243e-02  4.0753398e-02  6.7604296e-03  4.9387787e-02
  -3.9434541e-02 -1.6071606e-02 -3.6977123e-02 -4.4875395e-02
  -1.5914656e-02 -1.3506971e-02]
 [ 2.6188243e-02  4.0753398e-02  6.7604296e-03  4.9387787e-02
  -3.9434541e-02 -1.6071606e-02 -3.6977123e-02 -4.4875395e-02
  -1.5914656e-02 -1.3506971e-02]
 [ 2.6188243e-02  4.0753398e-02  6.7604296e-03  4.9387787e-02
  -3.9434541e-02 -1.6071606e-02 -3.6977123e-02 -4.4875395e-02
  -1.5914656e-02 -1.3506971e-02]
 [ 2.6188243e-02  4.0753398e-02  6.7604296e-03  4.9387787e-02
  -3.9434541e-02 -1.6071606e-02 -3.6977123e-02 -4.4875395e-02
  -1.5914656e-02 -1.3506971e-02]
 [ 3.6366869e-02 -4.6646643e-02  2.9428754e-02 -3.8586736e-02
  -1.0367483e-04 -3.0875206e-05 -2.0116402e-02  3.5556186e-02
   4.7567461e-02 -3.7932944e-02]
 [ 2.6406050e-03 -3.2696832e-02  1.5045892e-02  3.5047952e-02
   1.4321018e-02 -2.5825346e-02 -7.8846924e-03  3.4690905e-02
  -6.7549720e-03 -2.1972883e-02]
 [-4.6418525e-02 -9.8487362e-03  2.6200306e-02  1.5473556e

In [19]:
embedded_docs[1]

array([   0,    0,    0,    0, 9445, 5954, 1510, 8519])

In [21]:
model.predict((embedded_docs)[1])

array([[[ 2.6188243e-02,  4.0753398e-02,  6.7604296e-03,  4.9387787e-02,
         -3.9434541e-02, -1.6071606e-02, -3.6977123e-02, -4.4875395e-02,
         -1.5914656e-02, -1.3506971e-02]],

       [[ 2.6188243e-02,  4.0753398e-02,  6.7604296e-03,  4.9387787e-02,
         -3.9434541e-02, -1.6071606e-02, -3.6977123e-02, -4.4875395e-02,
         -1.5914656e-02, -1.3506971e-02]],

       [[ 2.6188243e-02,  4.0753398e-02,  6.7604296e-03,  4.9387787e-02,
         -3.9434541e-02, -1.6071606e-02, -3.6977123e-02, -4.4875395e-02,
         -1.5914656e-02, -1.3506971e-02]],

       [[ 2.6188243e-02,  4.0753398e-02,  6.7604296e-03,  4.9387787e-02,
         -3.9434541e-02, -1.6071606e-02, -3.6977123e-02, -4.4875395e-02,
         -1.5914656e-02, -1.3506971e-02]],

       [[ 3.6366869e-02, -4.6646643e-02,  2.9428754e-02, -3.8586736e-02,
         -1.0367483e-04, -3.0875206e-05, -2.0116402e-02,  3.5556186e-02,
          4.7567461e-02, -3.7932944e-02]],

       [[ 2.6406050e-03, -3.2696832e-02,  1.504589